package com.mfadhili.cheri.data.repository.autism_record;


import com.mfadhili.cheri.data.domain.autism_record.Autism_record;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface Autism_recordRepository extends JpaRepository<Autism_record, Long> {
    /** find all records assigned to a particular child. Generated by JPA Buddy*/
    @Query("select a from Autism_record a where a.children.id = ?1")
    List<Autism_record> findByChildren_Id(Long id);
}